# -*- coding: utf-8 -*-
"""quant_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiCbxTeu98TH4fm0Hn4QBOBLGOycvz1a
"""

# 1. 주식 데이터를 가져오는 도구(yfinance)를 설치해 줘!


# 2. 설치한 도구를 지금부터 쓸 수 있게 불러와 줘!
import yfinance as yf

# 3. 삼성전자(종목코드: 005930.KS)의 데이터를 가져와 줘!
samsung = yf.Ticker("005930.KS")

# 4. 최근 5일 동안의 주가 기록을 화면에 보여줘!
print(samsung.history(period="5d"))

import yfinance as yf
import pandas as pd

# 1. 삼성전자, 환율, 유가 티커(기호)를 리스트로 묶기
tickers = ['005930.KS', 'KRW=X', 'CL=F']

# 2. 3개 종목의 데이터를 한 번에 다운로드해서 '종가(Close)'만 뽑아오기
df = yf.download(tickers, period='1y')['Close']

# 3. 영어로 된 열 이름을 우리가 알아보기 쉽게 한글로 이름표 바꿔 달기
df = df.rename(columns={
    '005930.KS': '삼성전자',
    'KRW=X': '환율',
    'CL=F': '유가'
})

# 4. 주말이나 공휴일 때문에 생긴 빈칸(NaN) 줄 통째로 지우기
df = df.dropna()

# 5. 완성된 표의 최근 5일치 결과 확인하기!
print(df.tail())

# 1. 상관관계(Correlation) 숫자로 확인하기
print("=== 상관관계 점수 (1에 가까울수록 같이 움직임, -1은 반대로 움직임) ===")
print(df.corr())
print("\n") # 한 줄 띄우기

# 2. 세 가지 데이터의 출발점을 '100'으로 똑같이 맞추기 (단위 통일)
df_normalized = (df / df.iloc[0]) * 100

# 3. 그래프 그리기 도구 불러오기
import matplotlib.pyplot as plt

# 4. 한글 폰트 깨짐 방지를 위해 영어 라벨을 사용해서 그래프 그리기
plt.figure(figsize=(10, 5)) # 그래프 크기 설정 (가로 10, 세로 5)

plt.plot(df_normalized['삼성전자'], label='Samsung (Stock)', linewidth=2)
plt.plot(df_normalized['환율'], label='USD/KRW (Exchange)', linestyle='--')
plt.plot(df_normalized['유가'], label='WTI (Oil)', linestyle=':')

plt.title("1-Year Trend Comparison") # 그래프 제목
plt.legend() # 범례(이름표) 표시
plt.grid(True) # 격자무늬 추가
plt.show() # 화면에 출력!

import yfinance as yf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# 1. 데이터 가져오기 (5개 종목 한 번에)
tickers = ['005930.KS', '000660.KS', '011070.KS', 'KRW=X', 'CL=F']
df = yf.download(tickers, period='2y')['Close']
df = df.rename(columns={'005930.KS': '삼성전자', '000660.KS': 'SK하이닉스', '011070.KS': 'LG이노텍', 'KRW=X': '환율', 'CL=F': '유가'})
df = df.dropna()

# 2. 미래 예측을 위한 마법 (타겟 데이터 만들기)
# AI에게 "오늘 지표를 보고 '내일' 주가를 맞춰봐!"라고 학습시키기 위해, SK하이닉스 주가를 하루 위로 끌어올립니다.
df['내일_SK하이닉스'] = df['SK하이닉스'].shift(-1)
df = df.dropna() # 데이터가 없는 마지막 날 빈칸 지우기

# 3. 문제(X)와 정답(y) 나누기
X = df[['삼성전자', 'LG이노텍', '환율', '유가', 'SK하이닉스']] # 문제: 오늘의 모든 경제 지표들
y = df['내일_SK하이닉스'] # 정답: 내일의 SK하이닉스 주가

# 4. 학습용 데이터와 시험용 데이터 분리 (모의고사와 수능)
# 전체 데이터의 80%로 공부하고, 최근 20%의 데이터로 AI가 얼마나 잘 맞추는지 시험을 봅니다.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# 5. AI 모델 학습시키기 (선형 회귀 모델)
model = LinearRegression()
model.fit(X_train, y_train) # "공부 시작!" (최적의 가중치를 스스로 찾습니다)

# 6. 시험 보기 및 결과 채점 (최근 20% 기간 예측)
predictions = model.predict(X_test)

# 7. 결과 그래프로 그리기
plt.figure(figsize=(10,5))
plt.plot(y_test.values, label='Actual Price (SK Hynix)', linewidth=2)
plt.plot(predictions, label='AI Predicted Price', linestyle='--', color='red')
plt.title('SK Hynix AI Prediction vs Actual')
plt.legend()
plt.grid(True)
plt.show()

# 뉴스 데이터를 수집하는 도구(requests, BeautifulSoup) 불러오기
import requests
from bs4 import BeautifulSoup

# 1. 삼성전자 네이버 금융 뉴스 페이지 주소 설정
url = "https://finance.naver.com/item/news_news.naver?code=005930"
# (로봇이 아니라 사람인 척하기 위한 신분증)
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}

# 2. 웹페이지에 접속해서 내용 가져오기
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

print("=== 📡 실시간 삼성전자 최신 뉴스 제목 수집 ===")
# 3. 뉴스 제목이 있는 태그(위치)를 찾아서 5개만 뽑아오기
titles = soup.select('.title a')
for i, title in enumerate(titles[:5]):
    print(f"{i+1}. {title.text.strip()}")

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# 1. SK하이닉스 주가 데이터 가져오기
df = yf.download('000660.KS', period='2y')[['Close']]
df = df.dropna()

# 2. 데이터 압축하기 (정규화)
# 딥러닝 모델은 큰 숫자(예: 150,000원)를 싫어합니다. 모든 주가를 0과 1 사이의 비율로 압축해 줍니다.
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

# 3. 과거의 흐름 기억시키기 (Windowing)
# "과거 10일치 주가 흐름을 보고 -> 11일째 주가를 맞춰봐!" 형식으로 문제를 만듭니다.
window_size = 10
X, y = [], []
for i in range(len(scaled_data) - window_size):
    X.append(scaled_data[i : i+window_size]) # 문제 (과거 10일)
    y.append(scaled_data[i+window_size])     # 정답 (다음 날)

X, y = np.array(X), np.array(y)

# 4. 모의고사(학습용 80%)와 수능(테스트용 20%) 분리
split = int(len(X) * 0.8)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# 5. 🧠 대망의 LSTM 딥러닝 신경망 조립하기
model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(window_size, 1))) # 첫 번째 뇌세포 층
model.add(LSTM(50, return_sequences=False))                              # 두 번째 뇌세포 층
model.add(Dense(25)) # 생각 정리
model.add(Dense(1))  # 최종 결론(주가 예측)

# 6. 공부 시작!
model.compile(optimizer='adam', loss='mean_squared_error')
print("🔥 딥러닝 모델이 패턴을 학습 중입니다. (10초~30초 대기)...")
# epochs=30 은 문제집을 10번 반복해서 푼다는 뜻입니다.
model.fit(X_train, y_train, batch_size=16, epochs=10, verbose=0)
print("✅ 학습 완료!")

# 7. 수능 시험 보고 결과 그래프 그리기
predictions = model.predict(X_test)
# 0~1로 압축했던 결과를 다시 '원래 주가(원)' 단위로 부풀려서 복원합니다.
predictions = scaler.inverse_transform(predictions)
real_prices = scaler.inverse_transform(y_test)

plt.figure(figsize=(10, 5))
plt.plot(real_prices, label='Actual Price', linewidth=2)
plt.plot(predictions, label='LSTM Predicted Price', linestyle='--', color='red')
plt.title('SK Hynix: Deep Learning LSTM Prediction')
plt.legend()
plt.grid(True)
plt.show()

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# 1. 여러 데이터 한 번에 가져와서 하나의 표로 합치기
tickers = ['000660.KS', 'KRW=X', 'CL=F']
df = yf.download(tickers, period='2y')['Close']
df = df.rename(columns={'000660.KS': 'SK하이닉스', 'KRW=X': '환율', 'CL=F': '유가'})
df = df.dropna()

# 2. 🌟 핵심: 문제(X)와 정답(y) 따로 압축하기
# 변수가 여러 개일 때 나중에 정답만 원래 가격으로 예쁘게 복원하기 위한 '꼼수'입니다.
scaler_X = MinMaxScaler() # 문제 압축기
scaler_y = MinMaxScaler() # 정답 압축기

scaled_X = scaler_X.fit_transform(df) # 하이닉스, 환율, 유가 전부 압축
scaled_y = scaler_y.fit_transform(df[['SK하이닉스']]) # 하이닉스만 따로 압축

# 3. 과거 10일 치 '다변량' 데이터 묶기
window_size = 10
X, y = [], []
for i in range(len(scaled_X) - window_size):
    X.append(scaled_X[i : i + window_size]) # 문제: 10일 치의 [주가, 환율, 유가]
    y.append(scaled_y[i + window_size])     # 정답: 11일째의 주가

X, y = np.array(X), np.array(y)

# 4. 데이터 나누기 (80% 학습, 20% 시험)
split = int(len(X) * 0.8)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# 5. 다변량 LSTM 모델 만들기
model = Sequential()
# input_shape의 1이 X.shape[2](변수 개수=3개)로 바뀝니다! 이게 다변량의 핵심입니다.
model.add(LSTM(50, return_sequences=True, input_shape=(window_size, X.shape[2])))
model.add(LSTM(50, return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))

# 6. 학습 시작! (에포크 30번)
model.compile(optimizer='adam', loss='mean_squared_error')
print("🔥 환율과 유가까지 고려해서 복합적으로 생각 중입니다... (대기)")
model.fit(X_train, y_train, batch_size=16, epochs=30, verbose=0)
print("✅ 다변량 학습 완료!")

# 7. 시험 보기 및 찰흙 원상 복구
predictions = model.predict(X_test)
# 아까 따로 만들어둔 정답 압축기(scaler_y)를 쓰면 아주 쉽게 원래 '원' 단위로 돌아옵니다.
predictions = scaler_y.inverse_transform(predictions)
real_prices = scaler_y.inverse_transform(y_test)

# 8. 대망의 결과 그래프
plt.figure(figsize=(10, 5))
plt.plot(real_prices, label='Actual Price', linewidth=2)
plt.plot(predictions, label='Multivariate Predicted Price', linestyle='--', color='green')
plt.title('SK Hynix: Multivariate LSTM (Price + FX + Oil)')
plt.legend()
plt.grid(True)
plt.show()

# 1. 인공지능이 한글을 읽게 해주는 딥러닝 도구 설치
!pip install transformers torch

from transformers import pipeline

# 2. 서울대에서 만든 '한국어 금융 경제 뉴스 전용' AI 모델 불러오기
print("🤖 금융 AI 두뇌를 다운로드하고 있습니다... (최초 1회 대기)")
classifier = pipeline("text-classification", model="snunlp/KR-FinBert-SC")

# 3. 오늘자 시장 상황을 반영한 가상의 뉴스 제목들
news_list = [
            "SK하이닉스, 엔비디아에 HBM 추가 공급 '어닝 서프라이즈' 기대",
            "미국 CPI 물가 4.2% 쇼크... 코스피 외국인 자금 대량 이탈",
            "반도체 시장, 내년 하반기까지 뚜렷한 방향성 없이 관망세"
]

# 4. AI에게 뉴스를 읽히고 긍정/부정 점수 매기기
print("\n=== AI 뉴스 감성 분석 결과 ===")
for news in news_list:
    result = classifier(news)[0]
    label = result['label']

    # 문자를 수학 모델에 넣기 위해 숫자로 변환 (호재=1, 악재=-1, 중립=0)
    if label == 'positive':
        score = 1
    elif label == 'negative':
        score = -1
    else:
        score = 0

    print(f"📰 뉴스: {news}")
    print(f"👉 AI 판단: {label.upper()} (부여된 점수: {score}점)\n")

# (주의: 이전 셀에서 classifier를 이미 불러왔다면 첫 두 줄은 생략해도 됩니다)
from transformers import pipeline
classifier = pipeline("text-classification", model="snunlp/KR-FinBert-SC")

# 사용자가 요청한 극한의 매크로 뉴스 제목들
test_news = [
    "스페이스X 역대급 IPO 상장 후폭풍, 국내 기술주 수급 블랙홀 우려",
    "스페이스X 성공적 상장, 국내 우주항공 및 방산 밸류체인 동반 강세",
    "이란 전쟁 확전 양상, 호르무즈 해협 봉쇄 위기로 글로벌 유가 폭등 불가피"
]

print("=== 🚨 글로벌 매크로 뉴스 AI 감성 분석 테스트 ===")
for news in test_news:
    result = classifier(news)[0]
    label = result['label']

    # 모델에 넣기 위한 수치화
    if label == 'positive':
        score = 1
    elif label == 'negative':
        score = -1
    else:
        score = 0

    print(f"📰 뉴스 제목: {news}")
    print(f"👉 AI 분석 결과: {label.upper()} (점수: {score}점)\n")

import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from transformers import pipeline
import requests
import warnings
warnings.filterwarnings('ignore') # 보기 싫은 경고 메시지 숨기기

# ==========================================
# ⚙️ 1. 기본 설정 (여기를 본인 정보로 수정하세요!)
# ==========================================
TELEGRAM_TOKEN = "여기에_발급받은_토큰_입력"
CHAT_ID = "여기에_확인한_방번호_입력"

# 분석할 종목과 지표
TICKERS = ['000660.KS', 'KRW=X', 'CL=F'] # SK하이닉스, 환율, 유가

print("🚀 [System] AI 퀀트 자동화 파이프라인 가동을 시작합니다...")

# ==========================================
# 📊 2. 시장 데이터 수집 및 전처리
# ==========================================
print("▶️ 시장 데이터 수집 중...")
df = yf.download(TICKERS, period='2y')['Close']
df = df.dropna()

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

scaled_X = scaler_X.fit_transform(df)
scaled_y = scaler_y.fit_transform(df[['000660.KS']]) # SK하이닉스만

window_size = 10
X, y = [], []
for i in range(len(scaled_X) - window_size):
    X.append(scaled_X[i : i + window_size])
    y.append(scaled_y[i + window_size])

X, y = np.array(X), np.array(y)

# ==========================================
# 🧠 3. 다변량 LSTM 예측 모델 학습
# ==========================================
print("▶️ AI 모델이 최근 시장 맥락을 학습하고 있습니다 (약 20초 소요)...")
model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(window_size, X.shape[2])),
    LSTM(50, return_sequences=False),
    Dense(25),
    Dense(1)
])
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X, y, batch_size=16, epochs=20, verbose=0) # 최신 데이터까지 전부 학습

# 내일 주가 예측하기 (가장 최근 10일치 데이터를 넣어서 내일을 예측)
last_10_days = scaled_X[-window_size:].reshape(1, window_size, X.shape[2])
predicted_scaled = model.predict(last_10_days, verbose=0)
predicted_price = scaler_y.inverse_transform(predicted_scaled)[0][0]
current_price = df['000660.KS'].iloc[-1]
predict_trend = "상승 🔺" if predicted_price > current_price else "하락 🔻"

# ==========================================
# 📰 4. 뉴스 감성 분석 (KR-FinBert)
# ==========================================
print("▶️ 최신 뉴스 감성 분석 중...")
classifier = pipeline("text-classification", model="snunlp/KR-FinBert-SC")
news_list = [
    "스페이스X 역대급 IPO 상장 후폭풍, 국내 기술주 수급 블랙홀 우려",
    "이란 전쟁 확전 양상, 호르무즈 해협 봉쇄 위기로 글로벌 유가 폭등 불가피"
]

news_score = 0
for news in news_list:
    res = classifier(news)[0]['label']
    if res == 'positive': news_score += 1
    elif res == 'negative': news_score -= 1

sentiment_result = "호재 우위 ☀️" if news_score > 0 else ("악재 우위 ☔" if news_score < 0 else "중립 ☁️")

# ==========================================
# 📱 5. 텔레그램 리포트 전송
# ==========================================
print("▶️ 텔레그램으로 브리핑을 전송합니다...")

report = f"""
🤖 *[AI 퀀트 일일 브리핑]*

📈 *시장 매크로 요약*
- 환율 (KRW/USD): {df['KRW=X'].iloc[-1]:.1f}원
- 유가 (WTI): {df['CL=F'].iloc[-1]:.2f}달러
- SK하이닉스 종가: {int(current_price):,}원

📰 *AI 뉴스 감성 분석*
- 종합 판정: *{sentiment_result}* (점수: {news_score})

🔮 *LSTM 딥러닝 예측*
- 내일 예측가: *{int(predicted_price):,}원*
- AI 방향성 전망: *{predict_trend}*
"""

url_send = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
requests.post(url_send, json={"chat_id": CHAT_ID, "text": report, "parse_mode": "Markdown"})

print("✅ 모든 작업이 완료되었습니다! 텔레그램을 확인하세요.")

import os

# ❌ 잘못된 예시 (진짜 토큰을 넣거나 한글을 쓰면 에러가 납니다)
# TELEGRAM_TOKEN = os.environ['1234567:ABCDEFG...']
# TELEGRAM_TOKEN = ['여기에다 api입력']

# ⭕ 올바른 예시 (아래 줄을 토씨 하나 틀리지 않고 그대로 적으세요!)
TELEGRAM_TOKEN = os.environ['TELEGRAM_TOKEN']

